In [ ]:
 # Objective : Learning to solve basic Python problems
    # Module 1 listed .... - SQL

# Tackle few simple problems relevant to AI/ML

#   - Break a problem into smaller sub-problems.
#   - Connecting the dots from sub-problems to coding-concepts.
#   - Code-walkthrough + putting it all together.
#   - More focus on common errors and mistakes + reading .
#   - Exercise-problems for practice.
#   - Introduce new concepts as we need.

In [ ]:
#  Problem 1: Add two randomly generated Numpy matrices using loops
#   - Sub-problems
#   - Subproblem ----> Coding concepts
#   - Code-walkthrough + Mistakes
#   - Exercise: Add two randomly generated Numpy 3D-matrices(tensor) using loops

In [ ]:
#   create random matrix A1 of size 5X4
##  Google " numpy create random matrices" & Read through the top 4-5 links
import numpy as np
a1 = np.random.rand(5, 4) # first matrix
# COMMON-ERROR: np.random.rand(4,5) wrong way to use this one 
# print(a1)
# print(a1.shape)
# print(a1.dtype) # datatype of numpy array is using to store...
# print(type(a1)) # type functions 

a2 = np.random.rand(5, 4) # seconds matrix 
# print(a2)
# print(type(a2))
# print(a2.shape)
# print(a2.dtype)

# using loops for additions two matrices 
# b[i, j] = a1[i, j] + a2[i, j]
(r, c) = a1.shape #getting the shape of the matrix a1
b = np.zeros((r, c)) # assigning zeros to the matrix b for storing the result. (pre- allocate matrix B : OPTIMIZATION)
for i in range(r):
    for j in range(c):
        b[i, j] = a1[i, j] + a2[i, j]

print(b)

[[1.39752911 0.28106656 1.2517654  1.60176925]
 [1.09163095 1.35873052 0.71496602 0.46531215]
 [0.89036396 1.50607168 0.77768848 0.4563135 ]
 [1.16545617 1.70898738 0.74742402 1.04259908]
 [1.80529635 0.70960551 1.30048598 1.8015216 ]]


In [46]:
merge_matrix = a1 + a2 # one way of add two matrices : using operator on ndarrays.
print(merge_matrix)

[[1.39752911 0.28106656 1.2517654  1.60176925]
 [1.09163095 1.35873052 0.71496602 0.46531215]
 [0.89036396 1.50607168 0.77768848 0.4563135 ]
 [1.16545617 1.70898738 0.74742402 1.04259908]
 [1.80529635 0.70960551 1.30048598 1.8015216 ]]


In [47]:
# Time Complexity :  O(n^2) or you can say O(r*c)
# Space COmplexity : O(1)

In [ ]:
# Exercise : Add two randomly generated Numpy 3D-matrices(tensor) using loops?

# HINTS : b[i, j, k] = a1[i, j, k] + a2[i, j, k]
# 3D-matrix : (k, r, c)--> (depth, rows, columns)

import numpy as np
a1 = np.random.rand(3, 4, 2) # first 3D-matrix
a2 = np.random.rand(3, 4, 2) # second 3D-matrix
print(a1)
(k, r, c) = a1.shape #getting the shape of the matrix a1
b = np.zeros((k, r, c)) # assigning zeros to the matrix b for storing the result. (pre- allocate matrix B : OPTIMIZATION)
for k in range(k):
    for i in range(r):
        for j in range(c):
            b[k, i, j] = a1[k, i, j] + a2[k, i, j]

[[[0.92744666 0.19901442]
  [0.78162715 0.56068359]
  [0.26534661 0.25788818]
  [0.12890333 0.74923706]]

 [[0.98321856 0.17351298]
  [0.09673598 0.97650555]
  [0.86001412 0.06384902]
  [0.28174621 0.26887065]]

 [[0.23883629 0.07217722]
  [0.90192466 0.62710227]
  [0.56357508 0.13077032]
  [0.17962296 0.25987224]]]


In [ ]:
#  Problem 2: Find if a given 2D-point is inside (or) outside a circle ?
#   - Subproblem.
#   - Subproblem ---> coding concepts
#   - putting it all together.
#   - Exercise : Find if a given 2D point is inside (or) outside a rectangle?

In [ ]:
# check if P lies in circle
import math 
## String to Float: very important to note that split() return strings
# Inputs: Circle center (Cx, Cy), radius (r), and point (Px, Py)
Cx = float(input("Enter circle center x (Cx): ")) # 0
Cy = float(input("Enter circle center y (Cy): ")) # 0
r  = float(input("Enter radius of the circle: ")) # 5
Px = float(input("Enter point x (Px): ")) # 3
Py = float(input("Enter point y (Py): ")) # 4

# Calculate distance between point and center using math module
distance = math.sqrt((Px - Cx) ** 2 + (Py - Cy) ** 2)
print(distance)

# Check position
if distance < r:
    print("Point is inside the circle.")
elif distance == r:
    print("Point is on the circle.")
else:
    print("Point is outside the circle.")

Enter circle center x (Cx):  0.0
Enter circle center y (Cy):  0.0
Enter radius of the circle:  5
Enter point x (Px):  3
Enter point y (Py):  4


5.0
Point is on the circle.


In [3]:
# Exercise : Find if a point is inside or outside a rectangle
# HINT : How do you represent a rectangle ?

# Rectangle defined by bottom-left and top-right corners
# Take input for rectangle corners
x1 = float(input("Enter bottom-left x (x1): "))
y1 = float(input("Enter bottom-left y (y1): "))
x2 = float(input("Enter top-right x (x2): "))
y2 = float(input("Enter top-right y (y2): "))

# Take input for the point
px = float(input("Enter point x (px): "))
py = float(input("Enter point y (py): "))

# Check if the point is inside the rectangle
if x1 <= px <= x2 and y1 <= py <= y2:
    print("The point is inside the rectangle.")
else:
    print("The point is outside the rectangle.")


Enter bottom-left x (x1):  1
Enter bottom-left y (y1):  1
Enter top-right x (x2):  5
Enter top-right y (y2):  4
Enter point x (px):  32
Enter point y (py):  2


The point is outside the rectangle.


In [ ]:
# Problem 3 : NumPy ndarray manipulations operations.
# 1. Reshape matrices : very COMMON-ERRORS in assignments
import numpy as np
a = np.random.rand(5, 4)
print(a)

[[0.89519681 0.17409862 0.39699208 0.20819386]
 [0.85266079 0.53989055 0.68890273 0.21922724]
 [0.10629776 0.72125327 0.68910459 0.75554063]
 [0.14183435 0.497447   0.93818517 0.24271292]
 [0.30257226 0.7233226  0.65266372 0.95093934]]


In [26]:
# Reshape into a vector ("C":- row-major-order 
# Try patiently read the documentation and try alternative params
print(np.reshape(a, 20, 'C'))

[0.89519681 0.85266079 0.10629776 0.14183435 0.30257226 0.17409862
 0.53989055 0.72125327 0.497447   0.7233226  0.39699208 0.68890273
 0.68910459 0.93818517 0.65266372 0.20819386 0.21922724 0.75554063
 0.24271292 0.95093934]


In [27]:
print(np.reshape(a, 20, 'F')) # ('F'):- columns- major-order

[0.89519681 0.85266079 0.10629776 0.14183435 0.30257226 0.17409862
 0.53989055 0.72125327 0.497447   0.7233226  0.39699208 0.68890273
 0.68910459 0.93818517 0.65266372 0.20819386 0.21922724 0.75554063
 0.24271292 0.95093934]


In [28]:
print(np.reshape(a, (4, 5), 'A')) # ('A'):-  5X4 ---> 4X5

[[0.89519681 0.17409862 0.39699208 0.20819386 0.85266079]
 [0.53989055 0.68890273 0.21922724 0.10629776 0.72125327]
 [0.68910459 0.75554063 0.14183435 0.497447   0.93818517]
 [0.24271292 0.30257226 0.7233226  0.65266372 0.95093934]]


In [ ]:
# Exercise Problem: take a tensor size 4X5X6(tensor matrix) and convert it into a vector and matrix (10X12). 
import numpy as np 
a1 = np.random.rand(4, 5, 6)
print(a1)
print(a1.size)
print(type(a1))
print(np.ndim(a1)) # return the dimension of matrix

print()
print("***********************************************************")
print()

print()
print(np.reshape(a1, 120, 'C')) # 1-D matrix or vector 
print()
print("***********************************************************")
print()

print(np.reshape(a1, (20, 6), 'C')) # 2-D matrix

[[[0.03603807 0.75223872 0.8867435  0.68535616 0.93581989 0.98586406]
  [0.61345768 0.44844852 0.08108319 0.02627628 0.42908797 0.14582731]
  [0.8879344  0.93968839 0.05951432 0.75892407 0.98701654 0.70726766]
  [0.5548774  0.06415884 0.1088362  0.75039324 0.16465218 0.89351594]
  [0.04700626 0.87727999 0.56794738 0.63226828 0.70235085 0.45966483]]

 [[0.94607226 0.3102068  0.58989478 0.58451455 0.52835354 0.49952936]
  [0.53216271 0.10529164 0.05484458 0.33862773 0.19874005 0.05292193]
  [0.43453085 0.85953146 0.56493794 0.33495    0.71558143 0.89505481]
  [0.92054952 0.24724574 0.04554851 0.51107732 0.23062683 0.74559784]
  [0.60464371 0.90098912 0.16440925 0.96381368 0.74717119 0.67226623]]

 [[0.94087828 0.34713633 0.40247913 0.6394155  0.68807583 0.27297994]
  [0.99069509 0.16203927 0.84222341 0.64582881 0.82788962 0.1135143 ]
  [0.44760143 0.81349381 0.33284331 0.3574121  0.23223849 0.08279749]
  [0.76711131 0.15067482 0.54393092 0.30965865 0.34319286 0.62880132]
  [0.84625894 0.

In [67]:
#2 Stacking 
import numpy as np 
A = np.random.rand(5, 4)
B = np.random.rand(4, 4)

print(A)
print(B)

[[0.36256411 0.32249338 0.57006786 0.52566945]
 [0.37988787 0.04687629 0.94308316 0.28763604]
 [0.3322056  0.19611408 0.74727756 0.9886194 ]
 [0.24596577 0.30610537 0.17114934 0.6991066 ]
 [0.35899502 0.44092003 0.093233   0.76072051]]
[[0.15577125 0.42015874 0.20157571 0.67015232]
 [0.31907363 0.40537365 0.19620542 0.72915685]
 [0.08832673 0.08068863 0.9829082  0.03991595]
 [0.79326701 0.89152028 0.51508309 0.55314347]]


In [62]:
# C = [A B]
C = np.hstack((A, B)) # hstack:- horizontal stack / read documentation carefully 
print(C)

[[0.2107687  0.81959771 0.75468407 0.4094596  0.38024356 0.1676788 ]
 [0.46636605 0.05454859 0.73339336 0.06626969 0.68206886 0.54097243]
 [0.14500208 0.69661736 0.63306017 0.06638575 0.75657772 0.16429526]
 [0.35776568 0.7456776  0.92483313 0.85075813 0.97989186 0.16893271]
 [0.21918161 0.89904751 0.59646838 0.65953746 0.40263011 0.37753663]]


In [68]:
# C = [A B]
C = np.vstack((A, B)) # vstack:- Vertical stack / read documentation carefully
print(C)

[[0.36256411 0.32249338 0.57006786 0.52566945]
 [0.37988787 0.04687629 0.94308316 0.28763604]
 [0.3322056  0.19611408 0.74727756 0.9886194 ]
 [0.24596577 0.30610537 0.17114934 0.6991066 ]
 [0.35899502 0.44092003 0.093233   0.76072051]
 [0.15577125 0.42015874 0.20157571 0.67015232]
 [0.31907363 0.40537365 0.19620542 0.72915685]
 [0.08832673 0.08068863 0.9829082  0.03991595]
 [0.79326701 0.89152028 0.51508309 0.55314347]]


In [2]:
# 3D tensors
import numpy as np
a = np.random.rand(5, 4, 3) # (height, width, colors) in images is a good way to think of this
print(a.shape)
b = np.random.rand(5, 3, 3)
print(b.shape)

c = np.hstack((a, b))
print(c.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)
